# Generated by Django 4.2.7 on 2023-12-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbproject', '0004_category_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='language_logos/')),
            ],
        ),
    ]
